# Generated by Django 4.2.6 on 2024-02-19 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="updated",
            new_name="updated_at",
        ),
    ]
