# Generated by Django 4.2.6 on 2024-03-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0002_rename_created_user_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
