# Generated by Django 4.2.6 on 2024-03-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0003_alter_user_is_superuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
