# Generated by Django 4.2.6 on 2024-03-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0004_remove_user_is_staff_alter_user_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
