# Generated by Django 4.2.6 on 2024-03-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0007_alter_user_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
