# Generated by Django 4.2.6 on 2024-02-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_repository", "0002_category_repository_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="repository",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
