# Generated by Django 4.2.6 on 2024-02-27 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core_repository", "0003_alter_category_options_repository_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="user_repository",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="repository",
            name="author",
            field=models.CharField(max_length=255),
        ),
    ]
