# Generated by Django 4.2.6 on 2024-03-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_repository", "0004_repository_creator_alter_repository_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="description",
            field=models.TextField(max_length=1000),
        ),
    ]
